@startuml
' members definition
participant ConfigFile as cf
box TwitchLoader
    participant main as main
    participant websocket as ws
    participant listeners as navi
end box
participant TwitchApi as api
box TwitchConsumer_Mods
    participant consumerMain as naviMain
end box

participant Dusklight as dusk


' init
main -> main: initMod
activate main
    main -> cf : read settings.conf
    cf --> main : oauth key
    main -> ws: init socket
    ws -> api: boop
    api --> ws:
    ws --> main:
deactivate main

loop for each consummer
    naviMain -> naviMain: initMod
    activate naviMain
    note over naviMain: Thanks to export/import mechanic.\nTwitchConsumer mods will init after TwitchLoader
    deactivate naviMain
end


api -> ws: TwitchEvent (async, could happen at any time)
ws -> ws: socket.queue.add(event)

' update
note over main: updateMod is called each frame\nunrelated to fps, so its called at most 30 time per second
main -> main: updateMod
activate main
    main -> navi: if queue != empty
    navi -> navi: heyListen(TwitchEvent)
    activate navi
        loop for each consummer
            navi -> naviMain: heyListen(TwitchEvent)
            activate naviMain
                naviMain -> dusk: stuff specific to this given mod
                note over naviMain: Could also be a service for further nested behaviour\nNot forced to interact with dusklight
                dusk --> naviMain:
            deactivate naviMain
            naviMain-->navi
        end
    deactivate navi
    navi --> main:
    main -> main: queue->pop()
    note over main: the above arrow should be on the bar
deactivate main

naviMain->naviMain:updateMod
activate naviMain
    note over naviMain: i believe the updateMod is called with the same order as the init
deactivate naviMain

' destroy
loop for each consummer
    naviMain -> naviMain: shutdownMod
    activate naviMain
    note over naviMain: Thanks to export/import mechanic.\nTwitchConsumer mods will shutdown before TwitchLoader
    deactivate naviMain
end


main -> main: shutdownMod
activate main
    main->main:stop socket's thread
    main->main: delete socket
deactivate main
note over main: the above arrow should be on the bar
@enduml